### ISSUE TITLE
crash  after planting an bomb

### ISSUE THREAD

**Issue by panikajo** [swiftly-solution/swiftly_rank#2]
<details><summary>Details</summary>
<p>

[Swiftly] [Crash Reporter] A crash has occured and a dump has been created:
[Swiftly] [Crash Reporter]  0# 0x00007F9671D91FA8 in /home/container/game/csgo/addons/swiftly/bin/linuxsteamrt64/swiftly.so
[Swiftly] [Crash Reporter]  1# 0x00007F96C404DD60 in /lib/x86_64-linux-gnu/libc.so.6
[Swiftly] [Crash Reporter]  2# FetchPlayer(Player*, char const*) in /home/container/game/csgo/addons/swiftly/plugins/swiftly_rank/swiftly_rank.so
[Swiftly] [Crash Reporter]  3# OnPlayerDeath(Player*, Player*, Player*, bool, char const*, bool, short, short, short, short, bool, bool, bool, bool, float, short, short, short) in /home/container/game/csgo/addons/swiftly/plugins/swiftly_rank/swiftly_rank.so
[Swiftly] [Crash Reporter]  4# Internal_OnPlayerDeath in /home/container/game/csgo/addons/swiftly/plugins/swiftly_rank/swiftly_rank.so
[Swiftly] [Crash Reporter]  5# 0x00007F9671CC8513 in /home/container/game/csgo/addons/swiftly/bin/linuxsteamrt64/swiftly.so
[Swiftly] [Crash Reporter]  6# 0x00007F9671D042ED in /home/container/game/csgo/addons/swiftly/bin/linuxsteamrt64/swiftly.so
[Swiftly] [Crash Reporter]  7# 0x00007F9671CC673E in /home/container/game/csgo/addons/swiftly/bin/linuxsteamrt64/swiftly.so
[Swiftly] [Crash Reporter]  8# 0x00007F9679F28E56 in /home/container/game/bin/linuxsteamrt64/../../csgo/bin/linuxsteamrt64/libserver.so
[Swiftly] [Crash Reporter] A dump log file has been created at: addons/swiftly/dumps/crash.77a0e09d-7b6b-6856-2c73-913091065a85.log
[Swiftly] [Crash Reporter] A crash report has been sent to Swiftly Crash Reporter Server.
CNetworkSystem::CleanupDebugOutputFunction()

</p>
</details>

**Comment by blu133721** [comment]
Fixed in [#14](https://github.com/swiftly-solution/swiftly_rank/commit/203e05668904c7701808a13c2bf819e51e0b2c28)
